"""Initial migration

Revision ID: initial
Revises:
Create Date: 2023-04-19 10:30:45.123456

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = "initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # This will be auto-generated by alembic revision --autogenerate
    pass


def downgrade():
    # This will be auto-generated by alembic revision --autogenerate
    pass
